name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch_depth: 0
    # - name: Cache
    #   uses: actions/cache@v3
    #   id: cache
    #   with:
    #     path: |
    #       /nix/store/**
    #     key: ${{ runner.os }}-${{ github.sha }}
    #     restore-keys: |
    #       ${{ runner.os }}-
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: alexeldeib
    - uses: actions/setup-node@v3
      with:
        node-version: current
        cache: npm
    - run: npm install
    - run: commitlint --from=$(git rev-parse origin/main) -V
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
